apiVersion: v1
kind: Namespace
metadata:
  name: editor
  labels:
    app.kubernetes.io/part-of: ausome-ai-studio
---
apiVersion: v1
kind: Namespace
metadata:
  name: models
  labels:
    app.kubernetes.io/part-of: ausome-ai-studio
---
apiVersion: v1
kind: Namespace
metadata:
  name: agents
  labels:
    app.kubernetes.io/part-of: ausome-ai-studio
---
apiVersion: v1
kind: Namespace
metadata:
  name: workspaces
  labels:
    app.kubernetes.io/part-of: ausome-ai-studio
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    app.kubernetes.io/part-of: ausome-ai-studio
